# Generated by scripts/sync-release-from-fluxomni.py. Do not edit by hand.

generated_latest_public_release() {
  printf '%s\n' 'v26.2.4'
}

generated_public_release_alias() {
  case "$1" in
    v26.2.0|26.2.0)
      printf '%s\n' 'v0.10.1'
      ;;
    v26.2.1|26.2.1)
      printf '%s\n' 'v0.10.2'
      ;;
    v26.2.2|26.2.2)
      printf '%s\n' 'v0.11.0'
      ;;
    v26.2.3|26.2.3)
      printf '%s\n' 'v0.12.0'
      ;;
    v26.2.4|26.2.4)
      printf '%s\n' 'v0.13.0'
      ;;
    v0.10.1|0.10.1)
      printf '%s\n' 'v26.2.0'
      ;;
    v0.10.2|0.10.2)
      printf '%s\n' 'v26.2.1'
      ;;
    v0.11.0|0.11.0)
      printf '%s\n' 'v26.2.2'
      ;;
    v0.12.0|0.12.0)
      printf '%s\n' 'v26.2.3'
      ;;
    v0.13.0|0.13.0)
      printf '%s\n' 'v26.2.4'
      ;;
    *)
      return 1
      ;;
  esac
}
