# Generated by scripts/sync-release-from-fluxomni.py. Do not edit by hand.

generated_latest_public_release() {
  printf '%s\n' 'v2026.05.1'
}

generated_public_release_alias() {
  case "$1" in
    v2026.04.1|2026.04.1)
      printf '%s\n' 'v0.10.1'
      ;;
    v2026.04.2|2026.04.2)
      printf '%s\n' 'v0.10.2'
      ;;
    v2026.05.0|2026.05.0)
      printf '%s\n' 'v0.11.0'
      ;;
    v2026.05.1|2026.05.1)
      printf '%s\n' 'v0.12.0'
      ;;
    v0.10.1|0.10.1)
      printf '%s\n' 'v2026.04.1'
      ;;
    v0.10.2|0.10.2)
      printf '%s\n' 'v2026.04.2'
      ;;
    v0.11.0|0.11.0)
      printf '%s\n' 'v2026.05.0'
      ;;
    v0.12.0|0.12.0)
      printf '%s\n' 'v2026.05.1'
      ;;
    *)
      return 1
      ;;
  esac
}
