#!/usr/bin/env python3
"""Sync public release facts from a Fluxomni public release manifest."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "docs/src/release-manifest.json"
VERSION_MAP_PATH = ROOT / "scripts/generated-version-map.sh"
SCHEMA_OUT = ROOT / "docs/src/api/schema.graphql"
RECIPES_OUT = ROOT / "docs/src/api/automation-recipes.json"
LLMS_OUT = ROOT / "docs/src/api/llms.txt"
SYNC_STATE = ROOT / "docs/src/api/.fluxomni-sync.json"

EXAMPLE_SOURCES = [
    "api/examples/typescript/session-raw-subscription.ts",
    "api/examples/typescript/ensure-route-desired-state.ts",
    "api/examples/typescript/manage-route-controls.ts",
    "api/examples/typescript/manage-playlist-artifacts-settings-fleet.ts",
]

PUBLIC_DOC_SOURCES = [
    "api/schema.graphql",
    "api/clients/typescript/README.md",
    "docs/public-api/contract-inventory.md",
    "docs/public-api/error-taxonomy.md",
    "docs/public-api/fleet-command-safety.md",
    "docs/public-api/compatibility-policy.md",
]


def run(command: list[str], cwd: Path) -> str:
    return subprocess.check_output(command, cwd=cwd, text=True).strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_if_changed(path: Path, text: str, changed: list[str]) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        changed.append(str(path.relative_to(ROOT)))


def require_paths(fluxomni_root: Path) -> None:
    missing = [relative for relative in [*PUBLIC_DOC_SOURCES, *EXAMPLE_SOURCES] if not (fluxomni_root / relative).exists()]
    if missing:
        raise SystemExit("Missing required upstream release sources:\n" + "\n".join(f"- {item}" for item in missing))


def merge_manifest(existing: dict[str, Any] | None, incoming: dict[str, Any]) -> dict[str, Any]:
    releases = dict((existing or {}).get("releases", {}))
    incoming_releases = incoming.get("releases", {})
    # Canonical quarterly public identities replace the old date-style keys;
    # retained core tags remain the rollback boundary for released artifacts.
    if any(re.fullmatch(r"v\d{2}\.[1-4]\.\d+", key) for key in incoming_releases):
        releases = {
            key: release
            for key, release in releases.items()
            if not re.fullmatch(r"v\d{4}\.\d{2}\.\d+", key)
        }
    releases.update(incoming_releases)
    return {
        "schemaVersion": incoming.get("schemaVersion", 1),
        "latestStable": incoming["latestStable"],
        "releases": dict(sorted(releases.items())),
        "edge": incoming.get("edge", (existing or {}).get("edge", {})),
    }


def validate_manifest_matches_checkout(fluxomni_root: Path, manifest: dict[str, Any]) -> None:
    latest = manifest.get("latestStable")
    release = manifest.get("releases", {}).get(latest)
    if not latest or not isinstance(release, dict):
        raise SystemExit("Release manifest does not contain its latestStable release entry.")

    expected_schema_hash = release.get("api", {}).get("schemaSha256")
    if not expected_schema_hash:
        raise SystemExit(f"Release manifest for {latest} is missing api.schemaSha256.")

    actual_schema_hash = sha256(fluxomni_root / "api/schema.graphql")
    if actual_schema_hash != expected_schema_hash:
        raise SystemExit(
            "Release manifest schema hash does not match the Fluxomni checkout:\n"
            f"- manifest: {expected_schema_hash}\n"
            f"- checkout: {actual_schema_hash}"
        )

    package_json = load_json(fluxomni_root / "api/clients/typescript/package.json")
    package_ref = f"{package_json['name']}@{package_json['version']}"
    expected_package_ref = release.get("api", {}).get("typescriptClient")
    if package_ref != expected_package_ref:
        raise SystemExit(
            "Release manifest API client does not match the Fluxomni checkout:\n"
            f"- manifest: {expected_package_ref}\n"
            f"- checkout: {package_ref}"
        )


def render_version_map(manifest: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/sync-release-from-fluxomni.py. Do not edit by hand.",
        "",
        "generated_latest_public_release() {",
        f"  printf '%s\\n' '{manifest['latestStable']}'",
        "}",
        "",
        "generated_public_release_alias() {",
        '  case "$1" in',
    ]
    for public_version, release in sorted(manifest["releases"].items()):
        core = release["coreVersion"]
        lines.extend(
            [
                f"    {public_version}|{public_version.removeprefix('v')})",
                f"      printf '%s\\n' '{core}'",
                "      ;;",
            ]
        )
    seen_core: set[str] = set()
    for public_version, release in sorted(manifest["releases"].items()):
        core = release["coreVersion"]
        if core in seen_core:
            continue
        seen_core.add(core)
        lines.extend(
            [
                f"    {core}|{core.removeprefix('v')})",
                f"      printf '%s\\n' '{public_version}'",
                "      ;;",
            ]
        )
    lines.extend(["    *)", "      return 1", "      ;;", "  esac", "}", ""])
    return "\n".join(lines)


def title_from_example(relative: str) -> str:
    stem = Path(relative).stem
    return re.sub(r"\s+", " ", stem.replace("-", " ")).strip().capitalize()


def render_recipes(manifest: dict[str, Any]) -> str:
    latest = manifest["latestStable"]
    client = manifest["releases"][latest]["api"]["typescriptClient"]
    recipes = [
        {
            "id": Path(relative).stem,
            "title": title_from_example(relative),
            "source": relative,
        }
        for relative in EXAMPLE_SOURCES
    ]
    payload = {"schemaVersion": 1, "release": latest, "apiClient": client, "recipes": recipes}
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_llms(manifest: dict[str, Any]) -> str:
    latest = manifest["latestStable"]
    release = manifest["releases"][latest]
    return "\n".join(
        [
            "# Fluxomni Self-Host API",
            "",
            f"Stable public release: {latest}",
            f"Core runtime: {release['coreVersion']}",
            f"Core API client: {release['api']['typescriptClient']}",
            "GraphQL SDL: /api/schema.graphql",
            "Automation recipes: /api/automation-recipes.json",
            "",
            "Use the stable API docs, generated schema, and pinned TypeScript client version for automation against self-hosted Fluxomni instances. Treat fleet commands and destructive mutations as operator-confirmed actions.",
            "",
        ]
    )


def render_sync_state(fluxomni_root: Path, manifest: dict[str, Any]) -> str:
    files = {}
    for relative in [*PUBLIC_DOC_SOURCES, *EXAMPLE_SOURCES]:
        path = fluxomni_root / relative
        files[relative] = {"present": True, "sha256": sha256(path), "bytes": path.stat().st_size}
    resolved_sha = run(["git", "rev-parse", "HEAD"], fluxomni_root)
    updated_at = dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()
    if SYNC_STATE.exists():
        previous = load_json(SYNC_STATE)
        if (
            previous.get("release") == manifest["latestStable"]
            and previous.get("coreVersion") == manifest["releases"][manifest["latestStable"]]["coreVersion"]
            and previous.get("resolvedSha") == resolved_sha
            and previous.get("files") == files
        ):
            updated_at = previous.get("updatedAt", updated_at)
    payload = {
        "schemaVersion": 2,
        "release": manifest["latestStable"],
        "coreVersion": manifest["releases"][manifest["latestStable"]]["coreVersion"],
        "resolvedSha": resolved_sha,
        "updatedAt": updated_at,
        "files": files,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fluxomni-root", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--mode", choices=["check", "update"], default="check")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    fluxomni_root = Path(args.fluxomni_root).resolve()
    manifest_path = Path(args.manifest).resolve()
    require_paths(fluxomni_root)

    incoming = load_json(manifest_path)
    validate_manifest_matches_checkout(fluxomni_root, incoming)
    existing = load_json(MANIFEST_PATH) if MANIFEST_PATH.exists() else None
    merged = merge_manifest(existing, incoming)

    outputs = {
        MANIFEST_PATH: json.dumps(merged, indent=2, sort_keys=True) + "\n",
        VERSION_MAP_PATH: render_version_map(merged),
        SCHEMA_OUT: (fluxomni_root / "api/schema.graphql").read_text(encoding="utf-8"),
        RECIPES_OUT: render_recipes(merged),
        LLMS_OUT: render_llms(merged),
        SYNC_STATE: render_sync_state(fluxomni_root, merged),
    }

    changed: list[str] = []
    if args.mode == "check":
        for path, text in outputs.items():
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                changed.append(str(path.relative_to(ROOT)))
        if changed:
            print("Release sync drift detected:", file=sys.stderr)
            for item in changed:
                print(f"- {item}", file=sys.stderr)
            return 1
        print("Release sync outputs are current.")
        return 0

    for path, text in outputs.items():
        write_if_changed(path, text, changed)
    if changed:
        print("Updated release sync outputs:")
        for item in changed:
            print(f"- {item}")
    else:
        print("Release sync outputs are already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
